version: "3.9"

secrets:
  secrets:
    file: ./secrets.yml

services:
  karaoqueue:
    image: "phillipkhne/karaoqueue:latest"
    restart: always
    ports:
      - "127.0.0.1:8081:80" # Please put a reverse proxy in front of this
    environment:
      DEPLOYMENT_PLATFORM: Docker
      DBSTRING: mysql://user:pass@host:3306/database
      BASIC_AUTH_USERNAME: admin
      BASIC_AUTH_PASSWORD: changeme
      ENTRY_QUOTA: 3
      MAX_QUEUE: 20
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: changeme!
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: karaoqueue
      MARIADB_USER: karaoqueue
      MARIADB_PASSWORD: change