version: '2'
services:
  mongo:
    extends:
        file: docker-compose.yml
        service: mongo

  mongo-express:
    depends_on:
        - mongo
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
