on: [push, pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest    
    steps:
    - name: Python Code Style, Quality, and Lint
      uses: weibullguy/python-lint-plus@v1.12.0
      with:
        python-version: "3.10"
        architecture: "x64"
        use-flake8: true
        python-root-list: "backend"